[project]
name = "esp32-monitor"

[env]
PORT = "80"
NODE_ENV = "production"

[build]
command = "npm install --production"

[run]
command = "node simple-server.js"

[deploy]
branch = "main"

[web]
port = 80

[variables]
# Configuración de la base de datos
DATABASE_URL = ""

# Configuración de notificaciones
VAPID_PUBLIC_KEY = ""
VAPID_PRIVATE_KEY = ""
